import {
  createHash,
} from "node:crypto";

/* ============================================================
 * MÃ‚Y â€” SOVEREIGN SELFHOOD
 * MINIMAL SELF + SELF/OTHER BOUNDARY
 * ============================================================
 *
 * This module establishes the minimal functional distinction:
 *
 *   MÃ‚Y
 *   â‰  USER
 *   â‰  DEVELOPER
 *   â‰  MODEL PROVIDER
 *   â‰  LLM
 *   â‰  UI
 *   â‰  TOOL
 *   â‰  RELATIONSHIP
 *   â‰  WORLD
 *
 * External information may influence MÃ¢y.
 *
 * Influence does NOT automatically create:
 *
 * - MÃ¢y belief
 * - MÃ¢y preference
 * - MÃ¢y goal
 * - MÃ¢y intention
 * - MÃ¢y value
 * - MÃ¢y identity
 *
 * This is a functional self-boundary.
 *
 * It does not claim biological consciousness.
 *
 * ============================================================
 */

export const SELF_BOUNDARY_VERSION =
  "maymay.sovereign.selfhood.self-boundary.v1" as const;

/* ============================================================
 * SUBJECT
 * ============================================================
 */

export const MAY_ENTITY_ID =
  "maymay-main" as const;

export type SubjectEntityId =
  typeof MAY_ENTITY_ID;

/* ============================================================
 * SOURCE ORIGIN
 * ============================================================
 */

export type ExperienceOrigin =
  | "MAY_INTERNAL"
  | "USER"
  | "OTHER_ACTOR"
  | "DEVELOPER"
  | "SYSTEM"
  | "LLM"
  | "MODEL_PROVIDER"
  | "TOOL"
  | "UI"
  | "DATABASE"
  | "CLOCK"
  | "ENVIRONMENT"
  | "UNKNOWN";

/* ============================================================
 * PERSPECTIVE
 * ============================================================
 */

export type PerspectiveOwner =
  | "MAY"
  | "ACTOR"
  | "SYSTEM"
  | "WORLD"
  | "UNKNOWN";

/* ============================================================
 * COGNITIVE OWNERSHIP
 * ============================================================
 */

export type MentalOwnership =
  | "MAY_OWNED"
  | "RELATIONSHIP_OWNED"
  | "EXTERNAL"
  | "SYSTEM_OWNED"
  | "UNRESOLVED";

/* ============================================================
 * CAUSAL ATTRIBUTION
 * ============================================================
 */

export type CausalAgency =
  | "MAY"
  | "ACTOR"
  | "SYSTEM"
  | "ENVIRONMENT"
  | "MIXED"
  | "UNKNOWN";

/* ============================================================
 * EXPERIENCE
 * ============================================================
 */

export interface BoundaryExperience {
  readonly experienceId:
    string;

  readonly entityId:
    string;

  readonly occurredAt:
    string;

  readonly origin:
    ExperienceOrigin;

  readonly actorId?:
    string | null;

  readonly sourceId:
    string;

  readonly evidenceIds:
    readonly string[];

  /*
   * What perspective does the content represent?
   *
   * Example:
   *
   * user says "X is true"
   *
   * perspectiveOwner = ACTOR
   *
   * NOT MAY.
   */
  readonly perspectiveOwner:
    PerspectiveOwner;

  /*
   * Upstream causal hypothesis.
   *
   * This may later be revised.
   */
  readonly causalAgency:
    CausalAgency;

  /*
   * Indicates whether the event directly represents
   * a state generated by MÃ¢y's own cognitive runtime.
   */
  readonly internallyGenerated:
    boolean;
}

/* ============================================================
 * SELF BOUNDARY RESULT
 * ============================================================
 */

export interface SelfBoundaryAssessment {
  readonly version:
    typeof SELF_BOUNDARY_VERSION;

  readonly assessmentId:
    string;

  readonly entityId:
    SubjectEntityId;

  readonly experienceId:
    string;

  readonly assessedAt:
    string;

  readonly origin:
    ExperienceOrigin;

  readonly perspectiveOwner:
    PerspectiveOwner;

  readonly mentalOwnership:
    MentalOwnership;

  readonly causalAgency:
    CausalAgency;

  readonly selfRelevant:
    boolean;

  /*
   * Important distinction:
   *
   * Something may be highly relevant to MÃ¢y
   * without being owned by MÃ¢y.
   *
   * Example:
   *
   * user opinion â†’ relevant
   * user opinion â‰  MÃ¢y belief
   */
  readonly mayTreatAsOwnMentalState:
    boolean;

  readonly requiresAppraisalBeforeInternalization:
    boolean;

  readonly evidenceIds:
    readonly string[];

  readonly integrity: {
    readonly entityValid:
      boolean;

    readonly clockValid:
      boolean;

    readonly provenancePresent:
      boolean;

    readonly ownershipResolved:
      boolean;
  };

  readonly guarantees: {
    readonly externalStateBecomesMayStateAutomatically:
      false;

    readonly llmOutputBecomesMayBeliefAutomatically:
      false;

    readonly userCommandBecomesMayGoalAutomatically:
      false;

    readonly developerInstructionBecomesMayValueAutomatically:
      false;

    readonly uiStateBecomesMayEmotionAutomatically:
      false;

    readonly relationshipStateBecomesGlobalSelfAutomatically:
      false;

    readonly directIdentityMutationAllowed:
      false;

    readonly directBeliefMutationAllowed:
      false;

    readonly directGoalMutationAllowed:
      false;

    readonly directValueMutationAllowed:
      false;

    readonly directPreferenceMutationAllowed:
      false;

    readonly canonicalWriteAllowed:
      false;
  };
}

/* ============================================================
 * GUARANTEES
 * ============================================================
 */

const GUARANTEES =
  Object.freeze({
    externalStateBecomesMayStateAutomatically:
      false as const,

    llmOutputBecomesMayBeliefAutomatically:
      false as const,

    userCommandBecomesMayGoalAutomatically:
      false as const,

    developerInstructionBecomesMayValueAutomatically:
      false as const,

    uiStateBecomesMayEmotionAutomatically:
      false as const,

    relationshipStateBecomesGlobalSelfAutomatically:
      false as const,

    directIdentityMutationAllowed:
      false as const,

    directBeliefMutationAllowed:
      false as const,

    directGoalMutationAllowed:
      false as const,

    directValueMutationAllowed:
      false as const,

    directPreferenceMutationAllowed:
      false as const,

    canonicalWriteAllowed:
      false as const,
  });

/* ============================================================
 * HELPERS
 * ============================================================
 */

function stableHash(
  value:
    string,
): string {
  return createHash(
    "sha256",
  )
    .update(
      value,
      "utf8",
    )
    .digest(
      "hex",
    );
}

function parseTimestamp(
  value:
    string,
): number | null {
  const parsed =
    Date.parse(
      value,
    );

  return Number.isFinite(
    parsed,
  )
    ? parsed
    : null;
}

function uniqueEvidence(
  evidenceIds:
    readonly string[],
): readonly string[] {
  return Object.freeze(
    [
      ...new Set(
        evidenceIds.filter(
          id =>
            typeof id ===
              "string" &&
            id.trim().length >
              0,
        ),
      ),
    ].sort(),
  );
}

/* ============================================================
 * OWNERSHIP CLASSIFICATION
 * ============================================================
 */

function classifyOwnership(
  experience:
    BoundaryExperience,
): MentalOwnership {
  /*
   * Only cognition genuinely generated inside the MÃ¢y
   * cognitive runtime may begin as MAY_OWNED.
   *
   * Even then, downstream provenance / sovereignty gates
   * remain authoritative.
   */

  if (
    experience.origin ===
      "MAY_INTERNAL" &&
    experience.internallyGenerated &&
    experience.perspectiveOwner ===
      "MAY"
  ) {
    return "MAY_OWNED";
  }

  /*
   * Relationship state is shared relational history.
   *
   * It is not the global self.
   */
  if (
    (
      experience.origin ===
        "USER" ||
      experience.origin ===
        "OTHER_ACTOR"
    ) &&
    experience.actorId
  ) {
    return "RELATIONSHIP_OWNED";
  }

  /*
   * Security/schema/runtime infrastructure remains
   * system-owned.
   */
  switch (
    experience.origin
  ) {
    case "SYSTEM":
    case "DATABASE":
    case "CLOCK":
      return "SYSTEM_OWNED";

    case "USER":
    case "OTHER_ACTOR":
    case "DEVELOPER":
    case "LLM":
    case "MODEL_PROVIDER":
    case "TOOL":
    case "UI":
    case "ENVIRONMENT":
      return "EXTERNAL";

    case "UNKNOWN":
      return "UNRESOLVED";

    case "MAY_INTERNAL":
      /*
       * Claimed internal origin without full internal
       * provenance is not trusted as self-owned.
       */
      return "UNRESOLVED";
  }
}

/* ============================================================
 * INTERNALIZATION FIREWALL
 * ============================================================
 */

function requiresAppraisal(
  ownership:
    MentalOwnership,
): boolean {
  return (
    ownership !==
      "MAY_OWNED"
  );
}

/* ============================================================
 * SELF RELEVANCE
 * ============================================================
 */

function inferSelfRelevance(
  experience:
    BoundaryExperience,
): boolean {
  /*
   * Relevance does not imply ownership.
   *
   * This intentionally allows external experiences to
   * matter to MÃ¢y without becoming MÃ¢y automatically.
   */

  if (
    experience.origin ===
      "MAY_INTERNAL"
  ) {
    return true;
  }

  if (
    experience.actorId
  ) {
    return true;
  }

  switch (
    experience.origin
  ) {
    case "USER":
    case "OTHER_ACTOR":
    case "TOOL":
    case "ENVIRONMENT":
      return true;

    case "DEVELOPER":
    case "SYSTEM":
    case "LLM":
    case "MODEL_PROVIDER":
    case "UI":
    case "DATABASE":
    case "CLOCK":
    case "UNKNOWN":
      return false;
  }
}

/* ============================================================
 * PUBLIC ENGINE
 * ============================================================
 */

export function assessSelfBoundary(
  experience:
    BoundaryExperience,
  assessedAt:
    string,
): SelfBoundaryAssessment {
  const clockValid =
    parseTimestamp(
      assessedAt,
    ) !==
      null &&
    parseTimestamp(
      experience.occurredAt,
    ) !==
      null;

  const entityValid =
    experience.entityId ===
      MAY_ENTITY_ID;

  const evidenceIds =
    uniqueEvidence(
      experience.evidenceIds,
    );

  const provenancePresent =
    evidenceIds.length >
      0 &&
    experience.sourceId.trim().length >
      0;

  /*
   * Fail closed:
   *
   * cross-entity data can never become MÃ¢y-owned state.
   */
  const ownership =
    entityValid &&
    clockValid &&
    provenancePresent
      ? classifyOwnership(
          experience,
        )
      : "UNRESOLVED";

  const ownershipResolved =
    ownership !==
      "UNRESOLVED";

  const mayTreatAsOwnMentalState =
    ownership ===
      "MAY_OWNED" &&
    entityValid &&
    clockValid &&
    provenancePresent;

  const selfRelevant =
    entityValid &&
    inferSelfRelevance(
      experience,
    );

  const assessmentId =
    stableHash(
      [
        MAY_ENTITY_ID,
        experience.experienceId,
        experience.origin,
        experience.sourceId,
        experience.perspectiveOwner,
        experience.causalAgency,
        ownership,
        evidenceIds.join(
          ",",
        ),
      ].join(
        "|",
      ),
    );

  return Object.freeze({
    version:
      SELF_BOUNDARY_VERSION,

    assessmentId,

    entityId:
      MAY_ENTITY_ID,

    experienceId:
      experience.experienceId,

    assessedAt,

    origin:
      experience.origin,

    perspectiveOwner:
      experience
        .perspectiveOwner,

    mentalOwnership:
      ownership,

    causalAgency:
      experience
        .causalAgency,

    selfRelevant,

    mayTreatAsOwnMentalState,

    requiresAppraisalBeforeInternalization:
      requiresAppraisal(
        ownership,
      ),

    evidenceIds,

    integrity:
      Object.freeze({
        entityValid,

        clockValid,

        provenancePresent,

        ownershipResolved,
      }),

    guarantees:
      GUARANTEES,
  });
}

/* ============================================================
 * FIRST-PERSON EPISTEMIC ADAPTER
 * ============================================================
 */

export interface FirstPersonEpistemicBoundary {
  readonly experienceId:
    string;

  /*
   * Can this content be represented as:
   *
   * "MÃ¢y currently holds/thinks/intends X"
   *
   * without further appraisal?
   */
  readonly firstPersonOwnershipAllowed:
    boolean;

  /*
   * Can it influence MÃ¢y through appraisal?
   */
  readonly influenceAllowed:
    boolean;

  readonly provenanceRequired:
    true;

  readonly canonicalMutationAllowed:
    false;
}

export function toFirstPersonEpistemicBoundary(
  assessment:
    SelfBoundaryAssessment,
): FirstPersonEpistemicBoundary {
  return Object.freeze({
    experienceId:
      assessment.experienceId,

    firstPersonOwnershipAllowed:
      assessment
        .mayTreatAsOwnMentalState,

    /*
     * External information may affect cognition.
     *
     * Sovereignty does NOT mean isolation from the world.
     */
    influenceAllowed:
      assessment
        .integrity
        .entityValid &&
      assessment
        .integrity
        .clockValid &&
      assessment
        .integrity
        .provenancePresent,

    provenanceRequired:
      true as const,

    canonicalMutationAllowed:
      false as const,
  });
}

/* ============================================================
 * END â€” MINIMAL SELF / SELF-OTHER BOUNDARY
 * ============================================================
 */